apiVersion: v1
kind: Service
metadata:
  name: rectangles-api
  labels:
    app: rectangles-api
  annotations:
    networking.gke.io/load-balancer-ip-address: "34.42.155.192"
spec:
  type: LoadBalancer
  selector:
    app: rectangles-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080